### ISSUE TITLE
/users should show tg://user?id={user_id}

### ISSUE THREAD

**Issue by chelaxian** [F33RNI/GPT-Telegramus#107]
command "/users" should show "tg://user?id={user_id}" links instead of clear text with user ID.
we need some quick method to check if we know that user before ban.
we can't check it only by name and ID, beacuse name can be same for many users and IDs is hidden in tg clients.

opening tg:// links works from mobile tg clients.

or may be you can use https://t.me/{username} links if bot can get this info from users (not IDs)

**Comment by handsome0hell** [comment]
Thank you for your suggestion! We are discussing the details of this feature. See #109 for more information.

**Comment by handsome0hell** [comment]
> why not all user names in output of /users command has URL to user page? some of them has, some has not.

Are those group chats? There's no link for group chats.
