### ISSUE TITLE
ChatGPTModule.py in 4.0.0 not works

### ISSUE THREAD

**Issue by chelaxian** [F33RNI/GPT-Telegramus#116]
ChatGPTModule.py not work in 4.0.0 (other modules like Bing ai / Bing img / Bard / Gemini - works like a charm).
When I switch ChatGPTModule.py to previous version (3.7.0) - all works.

I think ChatGPTModule.py may have a problem in 4.0.0

It stops by timeout when ask chatgpt in 4.0.0 and /clear also not work in 4.0.0 with "time out" error

**Comment by F33RNI** [comment]
https://github.com/F33RNI/GPT-Telegramus/pull/117

**Comment by F33RNI** [comment]
Thanks for the issue! Apparently it was an import problem
