### ISSUE TITLE
please update new

### ISSUE THREAD

**Issue by Yoiapak96** [F33RNI/GPT-Telegramus#124]
A lot of function are left behind and don't work well. User JSON has a problem. /users command does not respond . many more issues please check.

**Comment by F33RNI** [comment]
What specifically isn't working for you?  Pls provide screenshots/logs

**Comment by F33RNI** [comment]
> A lot of function are left behind and don't work well. User JSON has a problem. /users command does not respond . many more issues please check.


Please answer what doesn't work for you, otherwise this issue will be closed due to inactivity

**Comment by Yoiapak96** [comment]
> What specifically isn't working for you? Pls provide screenshots/logs

![IMG_20240108_062149](https://github.com/F33RNI/GPT-Telegramus/assets/152215334/751c0a77-a8bd-4900-ba75-b80958dca78d)

**Comment by F33RNI** [comment]
Try updating the Telegram bot API token (create a new one via Bot Father) and if there are any errors, provide the logs

**Comment by F33RNI** [comment]
https://github.com/F33RNI/GPT-Telegramus/pull/144
