### ISSUE TITLE
Index out of range 

### ISSUE THREAD

**Issue by vpsbykaif** [F33RNI/GPT-Telegramus#129]
When I type /module or type the change module button I got an error here is the screen short:
![Screenshot_20240121_231638_Chrome](https://github.com/F33RNI/GPT-Telegramus/assets/149788775/7cda63e5-fb27-4bdd-aa52-3256cff5225c)

**Comment by F33RNI** [comment]
https://github.com/F33RNI/GPT-Telegramus/pull/144
