### ISSUE TITLE
Bard module not working

### ISSUE THREAD

**Issue by Deplyapp** [F33RNI/GPT-Telegramus#133]
The Bard module not working shows an error on every request I tried to change the cookie Value even I try to switch the google account and get the fresh cookie but it just shows the error here is the screenshot:

![Screenshot_20240127_120553_Telegram](https://github.com/F33RNI/GPT-Telegramus/assets/151662584/7e6f2852-fb75-40f9-82e9-badade413b15)

Logs screenshot:

![Screenshot_20240127_120957_Chrome](https://github.com/F33RNI/GPT-Telegramus/assets/151662584/e1b4aef0-9b2b-4398-ab36-1602eeddf13c)

**Comment by F33RNI** [comment]
https://github.com/F33RNI/GPT-Telegramus/pull/144
