### ISSUE TITLE
Add abillity to remove "New Chat"

### ISSUE THREAD

**Issue by chelaxian** [F33RNI/GPT-Telegramus#135]
Please add the abillity to remove "New Chat" tab in ChatGPT web-account after conversation is ended or reseted.
at first it looks very messy in web-account and difficult to find old chat that was started in web because of many chat with name "new Chat". at second - it breaks confidentiality of telegram users - if i can get access to their conversations in my web account.

you shoud think about deleting this "new chat" tabs from web after using /reset button

**Comment by F33RNI** [comment]
Now conversations are deleted correctly and there is no need for this
