### ISSUE TITLE
Add proxy option for Telegram.

### ISSUE THREAD

**Issue by Aqaao** [F33RNI/GPT-Telegramus#141]
Implementing this is simple. The following is the document of python-telegram-bot. Just load proxy url from `config.json` or 
environment variables.
https://github.com/python-telegram-bot/python-telegram-bot/wiki/Working-Behind-a-Proxy
```python
from telegram.ext import ApplicationBuilder

# "USERNAME:PASSWORD@" is optional, if you need authentication:
proxy_url = 'http://USERNAME:PASSWORD@PROXY_HOST:PROXY_PORT'  # can also be a https proxy
app = ApplicationBuilder().token("TOKEN").proxy(proxy_url).get_updates_proxy(proxy_url).build()
```

**Comment by F33RNI** [comment]
https://github.com/F33RNI/GPT-Telegramus/pull/160

**Comment by F33RNI** [comment]
Can u please check?

**Comment by Aqaao** [comment]
> #160
It work well. thank you😘.
