### ISSUE TITLE
❌ Error: Empty response!  Clear the history and make another request or try again later

### ISSUE THREAD

**Issue by chelaxian** [F33RNI/GPT-Telegramus#142]
ChatGPT gets prompts from telegram-bot and answer them in my web account,
But it doesn't  send back to telegram chat answers from web-chatgpt dialogue.

So i suppose all components like proxy, base url and access_token are working to 1 side - from tg-bot to openai server,
but it is not work from 2nd side - from openai to tg-bot.

What can i do to fix it?
Thanks!

```
❌ Error: Empty response!
Clear the history and make another request or try again later
```

<img width="412" alt="image" src="https://github.com/F33RNI/GPT-Telegramus/assets/69438111/68962dca-8157-4322-9ef6-d66f3e8abce8">

<img width="440" alt="image" src="https://github.com/F33RNI/GPT-Telegramus/assets/69438111/a16af0a7-3ef9-4df4-a827-8b9c39780ee5">

<img width="351" alt="image" src="https://github.com/F33RNI/GPT-Telegramus/assets/69438111/bf25d4fc-d6d6-4b27-8f99-736b100bcf5d">

**Comment by F33RNI** [comment]
https://github.com/F33RNI/GPT-Telegramus/pull/144
