### ISSUE TITLE
ARM64 not support google-chrome-stable

### ISSUE THREAD

**Issue by chelaxian** [F33RNI/GPT-Telegramus#147]
ARM64 not support google-chrome-stable

can you please add support of chromium-browser ?

```
chromium-browser is already the newest version (1:107.0.5304.62-0ubuntu1~ppa1~22.04.1).

chromium-browser --version
Chromium 107.0.5304.62 Ubuntu 22.04
```

**Comment by F33RNI** [comment]
https://github.com/F33RNI/LlM-Api-Open/commit/71a04f84a07653844e8060a600ccc4cd63935085

**Comment by F33RNI** [comment]
https://github.com/F33RNI/GPT-Telegramus/pull/148

**Comment by F33RNI** [comment]
Please check config in new release

**Comment by F33RNI** [comment]
Please provide logs

**Comment by F33RNI** [comment]
> [2024-03-12 12:45:46] [829090 ] [ERROR  ] chatgpt initialization error
> Traceback (most recent call last):
>   File "/root/github/GPT/GPT-Telegramus/venv/lib/python3.10/site-packages/lmao/module_wrapper.py", line 84, in _initialization_thread
>     self._module_class.session_start(**kwargs)
>   File "/root/github/GPT/GPT-Telegramus/venv/lib/python3.10/site-packages/lmao/chatgpt/chatgpt_api.py", line 358, in session_start
>     raise e
>   File "/root/github/GPT/GPT-Telegramus/venv/lib/python3.10/site-packages/lmao/chatgpt/chatgpt_api.py", line 236, in session_start
>     cookies_file = self.config.get("cookies_file")
> AttributeError: 'list' object has no attribute 'get

Your `config.json` file is not valid. It must be dictionary not list

**Comment by F33RNI** [comment]
Make sure you have read, write and execute permissions on your browser's executable

**Comment by F33RNI** [comment]
You can try 

```shell
sudo chmod 777 root/.local/share/undetected_chromedriver/undetected_chromedriver
```

**Comment by F33RNI** [comment]
Please try to install any other chromium-based browser and check if it works properly before using lmao api

**Comment by F33RNI** [comment]
Did you tried this? https://stackoverflow.com/a/53952226
