### ISSUE TITLE
STOP BOT feature

### ISSUE THREAD

**Issue by chelaxian** [F33RNI/GPT-Telegramus#151]
Can you please add /STOP command to IDLE bot in private chat group.
Because now bot answers to all messages in private group chat if Group Privacy is ON or bot is admin,
also bot not answers to any messages if Group Privacy is OFF (even when directly reply to its posts or using /commands@bot_name).

I think adding /STOP (or maybe /idle or /mute or whatever else) command to stop answering in Group Chat and /START to start answering in chat would be OK.

**Comment by F33RNI** [comment]
Please see this options inside `config.json`

```json
"__comment11__": "Set to true for the bot to reply to messages as well as direct module commands",
"reply_to_messages": true,
```

And also see the `/chat` command
