### ISSUE TITLE
Not work without any errors

### ISSUE THREAD

**Issue by abhpc** [F33RNI/GPT-Telegramus#18]
Install with command:
```
pip3.9 install -r requirements.txt --upgrade
```
and the setting.json is configured accordingly.

Then, I run it using command "python3.9 main.py", and the output is below without any errors:
```
2023-03-03 03:26:30 INFO     Proxy checks disabled. Initializing chatbot...
2023-03-03 03:26:30 INFO     AIHandler thread: Thread-1
2023-03-03 03:26:30 INFO     Responses handler background thread: Thread-2
2023-03-03 03:26:31 INFO     Application started
```
However, the telegram bot does not work without any responses.

**Comment by F33RNI** [comment]
The line `Application Started` means that the polling of the bot is started and it should answer your messages. Please check your telegram bot token and whether you write to the right bot

**Comment by F33RNI** [comment]
And pls write your OS, architecture etc... Because on my `GNU/Linux 5.15.0-48-generic x86_64`, `Python 3.10.6` everything works fine even without proxy

**Comment by F33RNI** [comment]
Try to update Python to 3.10
