### ISSUE TITLE
Problem with creating .log file

### ISSUE THREAD

**Issue by kantmrv** [F33RNI/GPT-Telegramus#25]
logging_setup(config["files"]["logs_dir"])
                  ~~~~~~^^^^^^^^^
TypeError: 'NoneType' object is not subscriptable

**Comment by F33RNI** [comment]
Do you have the correct path to the `config.json` file?
(This file must be in the folder with the main script, or it can be specified as an `--config path_to_config.json` argument)

**Comment by F33RNI** [comment]
It's not a problem with *creating .log file*, it's a problem with reading config

config is an object of type dict that is loaded from the json file on this line:
[`config = load_json(args.config, logging_enabled=False)`](https://github.com/F33RNI/GPT-Telegramus/blob/master/main.py#L99)

So, for this to work, you must specify the correct `config.json` file. 

You can test this by adding this line:
```python
print("args.config:", args.config, "config:", config)
```
after [`config = load_json(args.config, logging_enabled=False)`](https://github.com/F33RNI/GPT-Telegramus/blob/master/main.py#L99)

**Comment by kantmrv** [comment]
You right. There is a error in path. One letter is missed

**Comment by kantmrv** [comment]
I solvo problem. Thank you very much

**Comment by F33RNI** [comment]
That's nice!
If you have more questions, feel free to create a new issue.
