### ISSUE TITLE
To call when needed in chats

### ISSUE THREAD

**Issue by amitsha1** [F33RNI/GPT-Telegramus#32]
Sir, it is very impressing but there will be more comfort as we can call it when needed with specific command in chats as now it is replying to all massage.
thanks sir

**Comment by F33RNI** [comment]
Firstly, look at my pronouns in my profile.  I'm not a "sir".  

Secondly, I don't understand what you're talking about.  Do you want the bot to just send messages without replying to them?  If so, I can add it

**Comment by amitsha1** [comment]
Sorry mam,
My poin is that ini chats bot is replying to all massage even it is not for It 
so is it possible to add some features that when we hit some prefix than only bot responds
like /b or /g as prefix to call bot

**Comment by Yas-lab** [comment]
> Sorry mam, My point is that ini chats bot is replying to all massage even it is not for It so is it possible to add some features that when we hit some prefix than only bot responds like /b or /g as prefix to call bot

Dear Amitsha!

As far as i can see it, you would like to add telegramus to a group chat and in order to still be able to chat with "alive" users you want the bot to have a some kind of mode - answer only if you were asked with specific prefix of command?

Please advise if that's the case.

**Comment by amitsha1** [comment]
yes mam exactly 
Because now it is responding to all massage even it is not meant for it so if it is possible to add some prefix to call when needed it will be best for bot so that and it will enhanced its user experience in chats.
Thanks

**Comment by F33RNI** [comment]
https://github.com/F33RNI/GPT-Telegramus/pull/33/commits/a265c62859bcef68c615cee5e5e90c910e72b22a

**Comment by F33RNI** [comment]
[Release](https://github.com/F33RNI/GPT-Telegramus/releases/latest)

**Comment by amitsha1** [comment]
man,
How to  add prefix /G instead of Cursor character
as in chats its not convenient. 
Thanks
