### ISSUE TITLE
Modify code for running 24/7

### ISSUE THREAD

**Issue by whatthejames** [F33RNI/GPT-Telegramus#37]
Sir add a simple code in last of your original code so that we can ping it and run 24/7

**Comment by whatthejames** [comment]
> I didn't quite understand your question. The bot does not have to be launched from a terminal session, [you can run bot as service](https://github.com/F33RNI/GPT-Telegramus#-running-as-service-on-linux)

Just suggest me some free platform to run your bot sir.

**Comment by F33RNI** [comment]
First, stop calling me "sir" pls. Look at the pronouns in my profile

And I can't recommend you any platform. Personally, I run my bot on an old PC running 24/7 as a server powered by linux. Just google online servers to run telegram bots, if you want it

**Comment by whatthejames** [comment]
> Сlosing this Issue. This has nothing to do with GPT-Telegramus and is neither a bug nor a feature. If someone thinks otherwise, write a comment below.

I agree sir u can close it.
