### ISSUE TITLE
I did not understand 

### ISSUE THREAD

**Issue by kaifsarkar123** [F33RNI/GPT-Telegramus#39]
I did not understand the edge gpt in config.json I have to add a file called config.json or I do not change anything in edgegpt settings I have to add a cookie.json

**Comment by F33RNI** [comment]
EdgeGPT is a name for bing.com/chat. Please read more [here](https://github.com/acheong08/EdgeGPT)

In `config.json` (in `cookies_file` in `edgegpt`) you need to specify path to some `.json` file (you need to create it by yourself) with cookies inside it. So you need to create any json file (ex. `EdgeGPT_cookies.json`) paste cookies from your browser from bing.com/chat to that file and specify it in `config.json`

**Comment by kaifsarkar123** [comment]
Can I host the bot in docker hub so it runs continuously
