### ISSUE TITLE
The commands in the telegram

### ISSUE THREAD

**Issue by Wellmare** [F33RNI/GPT-Telegramus#46]
Why isn't the bot pinning commands in the telegram menu?
![image](https://github.com/F33RNI/GPT-Telegramus/assets/101342758/ece9a532-06c9-45ee-941d-15baadfa9eff)

Example menu with commands:
![image](https://github.com/F33RNI/GPT-Telegramus/assets/101342758/16c701ee-3ea0-4ecd-98e0-166c6ddb2f45)

**Comment by F33RNI** [comment]
Added to the [TODO list](https://github.com/F33RNI/GPT-Telegramus#-todo)
