### ISSUE TITLE
Some kind of error :(

### ISSUE THREAD

**Issue by Mailovskii** [F33RNI/GPT-Telegramus#47]
![image](https://github.com/F33RNI/GPT-Telegramus/assets/132333972/20b4f3a8-9a4f-4a47-b79f-b2666204a13d)
ubuntu 20.04

**Comment by Mailovskii** [comment]
Just to clarify, it worked the first time on Win10, but when I tried to run it on ubuntu, this error appeared.

**Comment by straferx** [comment]
I have the exact same issue, tried on ubuntu 20.04 and 22.04 - the same result. Also worked well on Win10

**Comment by F33RNI** [comment]
No problems on Ubuntu 22.04.2 LTS (GNU/Linux 5.15.0-78-generic x86_64)

**Comment by F33RNI** [comment]
Are you running on ARM?

**Comment by F33RNI** [comment]
As I can see on your first screenshot it's something with `python-telegram-bot` library, not GPT-Telegramus

It might be worth trying an older version of this library

**Comment by straferx** [comment]
> As I can see on your first screenshot it's something with `python-telegram-bot` library, not GPT-Telegramus
> 
> It might be worth trying an older version of this library

Sure, I updated the Python version to 3.10 and telegram library, it worked

**Comment by F33RNI** [comment]
So, have you solved this issue?
