### ISSUE TITLE
Can it continue the dialogue and connect with the context?

### ISSUE THREAD

**Issue by newt7744** [F33RNI/GPT-Telegramus#5]

**Comment by newt7744** [comment]
![image](https://user-images.githubusercontent.com/114227318/219334994-61172ae2-0896-4b72-9edf-a1bf84e143ed.png)
parent_message_id may useful

**Comment by F33RNI** [comment]
Thx! I added this.
You can set initial conversation id as `chatgpt_conversation_id` in `settings.json` (Every cycle it will be remembered)

Check, please

**Comment by F33RNI** [comment]
Oh, sorry, I just now realized that we also need `parent_id`. I'll implement it now...

**Comment by F33RNI** [comment]
Now it works. You can set initial conversation_id and parent_id like this:

```json
  "chatgpt_conversation_id": "d06d8fb8-4fa3-4837-....",
  "chatgpt_conversation_id__comment__": "INITIAL conversation_id",

  "chatgpt_parent_id": "f5da0c03-015f-49b3-....",
  "chatgpt_parent_id__comment__": "INITIAL parent_id",

```

Test:

![image](https://user-images.githubusercontent.com/39090123/219418832-272f31a4-c04c-4368-b236-c017db8fff0e.png)

**Comment by F33RNI** [comment]
In the future i think it would be nice to save each telegram chat with a separate `conversation_id` and `parent_id` to some sort of database so that several users can use chat independently

**Comment by newt7744** [comment]
That's great, I'm going to update and experience it now.

**Comment by newt7744** [comment]
maybe you are right. i just test without chatgpt_parent_id, but provided chatgpt_conversation_id,It can contact the context normally.
![image](https://user-images.githubusercontent.com/114227318/219533126-cf095ba0-338a-4099-badb-66cdc1369b23.png)

**Comment by qiangweihewu** [comment]
Where to get these IDs? Telegram or ChatGPT?

**Comment by F33RNI** [comment]
> Where to get these IDs? Telegram or ChatGPT?

Set them initially to `""` (empty). Write any question and look into logs in console for `Current conversation ID:`
