### ISSUE TITLE
bing image gen not woriking 

### ISSUE THREAD

**Issue by kaifsarkar123** [F33RNI/GPT-Telegramus#61]
the bing image is not working

"❌ Error clearing chat history!

Error.init() missing 3 required positional arguments: 'location', 'status_code', and 'details"

this error is coming in my telegram

**Comment by F33RNI** [comment]
Bing Image Generator has no history. How did you try to clean it up? 🙃
![image](https://github.com/F33RNI/GPT-Telegramus/assets/39090123/5d477d2f-b67e-464b-a615-b1c0e0776830)

**Comment by F33RNI** [comment]
Both EdgeGPT (aka Bing) and Bing ImageGen are working today. I don't have any problems. Please install latest versions of all packages, update your system and python version. Export latest cookies from Edge browser and use the same IP for Edge browser and bot and try again

**Comment by kaifsarkar123** [comment]
Ok thanks I have the problem in bing
