### ISSUE TITLE
i have an issue in edge gpt

### ISSUE THREAD

**Issue by kaifsarkar123** [F33RNI/GPT-Telegramus#62]
❌ Error: 'conversationSignature'

Make another request or try again later

I have tried every thing but it not work

**Comment by F33RNI** [comment]
The same.  I don't know what the problem is yet.  This appeared 2 days ago

**Comment by alfsoft** [comment]
I was able to fix this by using `git+https://github.com/jacobgelling/EdgeGPT@main#egg=EdgeGPT` in `requirements.txt` instead of `EdgeGPT==0.13.2` as it has fixes for this issue. Also I did `pip install -r requirements.txt --upgrade --force-reinstall` once to force package reinstallation.

**Comment by kaifsarkar123** [comment]
Thanks for the help 😁

> I was able to fix this by using `git+https://github.com/jacobgelling/EdgeGPT@main#egg=EdgeGPT` in `requirements.txt` instead of `EdgeGPT==0.13.2` as it has fixes for this issue. Also I did `pip install -r requirements.txt --upgrade --force-reinstall` once to force package reinstallation.

**Comment by F33RNI** [comment]
> I was able to fix this by using `git+https://github.com/jacobgelling/EdgeGPT@main#egg=EdgeGPT` in `requirements.txt` instead of `EdgeGPT==0.13.2` as it has fixes for this issue. Also I did `pip install -r requirements.txt --upgrade --force-reinstall` once to force package reinstallation.

Thank you very much!  It really worked!   I'll include this in the requirements by default.  Or, if you want you can open a pull request and add yourself to the contributors list 💜

**Comment by F33RNI** [comment]
Maybe someone knows how to also make Bard work again...?

**Comment by alfsoft** [comment]
> Or, if you want you can open a pull request and add yourself to the contributors list 💜
I will gladly contribute in your wonderful project =)

**Comment by F33RNI** [comment]
https://github.com/F33RNI/GPT-Telegramus/pull/63

**Comment by kaifsarkar123** [comment]
> Maybe someone knows how to also make Bard work again...?

Bard is already working

**Comment by F33RNI** [comment]
Am I the only one whose EdgeGPT history has stopped working?

**Comment by kaifsarkar123** [comment]
i edgegpt is woring fine but when I ask a something in first it works fine but after I have the clear the history of edge gpt then it work other wise it is sending the error


❌ Error: UnauthorizedRequest: Token is not authorized for this conversation.

Make another request or try again later

**Comment by F33RNI** [comment]
And the same error even if I update the cookies manually from the Edge browser after the first request

**Comment by F33RNI** [comment]
I managed to fix this error by preserving and setting the `encrypted_conversation_signature`. I'll release the fix soon. Stay tuned!

**Comment by F33RNI** [comment]
https://github.com/jacobgelling/EdgeGPT/pull/1

**Comment by F33RNI** [comment]
https://github.com/F33RNI/GPT-Telegramus/pull/66

**Comment by F33RNI** [comment]
https://github.com/F33RNI/GPT-Telegramus/releases/tag/3.5.1
