### ISSUE TITLE
CaptchaChallenge with bing ai

### ISSUE THREAD

**Issue by shakibalmolik** [F33RNI/GPT-Telegramus#68]
![20231010_201818.jpg](https://github.com/F33RNI/GPT-Telegramus/assets/80681198/0e473c97-6ad2-4a05-ac83-040d00f25642)

❌ Error: CaptchaChallenge: User needs to solve CAPTCHA to continue.

**Comment by F33RNI** [comment]
This happens from time to time.  Please update your cookies and do not use the browser version at the same time with the bot

**Comment by F33RNI** [comment]
Due to Bing updates, it is now very unstable.  Clearing the history often helps, but not always.  Looks like microsoft is fighting against unofficial usage

**Comment by kaifsarkar123** [comment]
I just want to ask that how everyone will use the bot at the same time as when one user asking the question to any model at the same time if 2nd user will try to use the bot it will make the request in que how to actually make both working at the same time

**Comment by F33RNI** [comment]
> I just want to ask that how everyone will use the bot at the same time as when one user asking the question to any model at the same time if 2nd user will try to use the bot it will make the request in que how to actually make both working at the same time

How do you imagine multiple people using one module at the same time?  This is why there is a queue so that processing takes 1 request/module
