### ISSUE TITLE
chat GPT  is not working

### ISSUE THREAD

**Issue by nani771** [F33RNI/GPT-Telegramus#7]
When starting the bot, such an error is displayed

[error.txt](https://github.com/F33RNI/GPT-Telegramus/files/10775100/error.txt)

**Comment by F33RNI** [comment]
In what country do you live?

**Comment by F33RNI** [comment]
and for the future... please don't copy your tokens and password here [🙃](https://emojipedia.org/upside-down-face/)

**Comment by nani771** [comment]
> В какой стране ты живешь?

I live in Ukraine should I use a proxy?

**Comment by nani771** [comment]
> и на будущее... пожалуйста, не копируйте сюда свои токены и пароль[🙃](https://emojipedia.org/upside-down-face/)


Thanks for telling me I didn't pay attention to that

**Comment by F33RNI** [comment]
> > В какой стране ты живешь?
> 
> I live in Ukraine should I use a proxy?

I think so. It doesn't work in my country either. But unfortunately it is very difficult to find a proxy with which it will work. I'm trying to code auto download proxy lists and check them, but it will take some time

Думаю да, проекси свтоит попробовать. В моей стране это тоже не работает и очень трудно найти прокси с которым оно будет жить. Я пытаюсь сделать автоматическое скачивание прокси-листов но это займёт время...

**Comment by F33RNI** [comment]
Ok I made automatic proxy loading and connection check, and also changed a lot of settings. Now the proxies are applied themselves.

But we need to wait for this pull request: https://github.com/acheong08/OpenAIAuth/pull/12
Without it, the proxies in the OpenAIAuth library didn't do anything haha

You can preview updates in this branch:
https://github.com/F33RNI/GPT-Telegramus/tree/beta_1.4.0

After my [Pull](https://github.com/acheong08/OpenAIAuth/pull/12) to OpenAIAuth is merged i will release new version

**Comment by F33RNI** [comment]
https://github.com/F33RNI/GPT-Telegramus/pull/8

**Comment by F33RNI** [comment]
Thanks for creating this issue. This prompted me to make an automatic download of the proxy list)

Now download the new version, set `enabled` in `proxy` to `true`, run it and wait. I found a working server after 20 minutes...
