### ISSUE TITLE
switch off showing sources in bing

### ISSUE THREAD

**Issue by Eikosa** [F33RNI/GPT-Telegramus#70]
the ability to switch off showing sources because it fills too many chars in message

**Comment by F33RNI** [comment]
![image](https://github.com/F33RNI/GPT-Telegramus/assets/39090123/d7cee36c-0178-4b7c-8449-d7ea44a0f997)

**Comment by F33RNI** [comment]
GPT-Telegramus automatically splits a long reply into multiple messages
