### ISSUE TITLE
write the number of messages

### ISSUE THREAD

**Issue by Eikosa** [F33RNI/GPT-Telegramus#76]
the feature of writing the number of conversation messages under the messages for bing or on the button, such as 10/30

**Comment by F33RNI** [comment]
![image](https://github.com/F33RNI/GPT-Telegramus/assets/39090123/14e173ce-c924-499c-843d-59a6efefae75)

**Comment by F33RNI** [comment]
GPT-Telegramus does not have a "daily" message limit. You can see the total number of user's requests by typing `/users`
