### ISSUE TITLE
bing completely misinterprets the picture

### ISSUE THREAD

**Issue by Eikosa** [F33RNI/GPT-Telegramus#78]
when I ask the same picture from bing web, it interprets it correctly, but when I ask it from the bot, it interprets it incorrectly, completely irrelevantly

**Comment by F33RNI** [comment]
The Bing AI (aka EdgeGPT) module does not yet accept images as input. This is written in the README

**Comment by kaifsarkar123** [comment]
It is not an issue but I just want to ask that how everyone will use the bot at the same time as when one user asking the question to any model at the same time if 2nd user will try to use the bot it will make the request in que how to actually make both working at the same time

**Comment by F33RNI** [comment]
> It is not an issue but I just want to ask that how everyone will use the bot at the same time as when one user asking the question to any model at the same time if 2nd user will try to use the bot it will make the request in que how to actually make both working at the same time

How do you imagine multiple people using one module at the same time?  This is why there is a queue so that processing takes 1 request/module

**Comment by Eikosa** [comment]
![image](https://github.com/F33RNI/GPT-Telegramus/assets/20538090/0fe1cc14-d42e-4991-a0a9-a2fa782bb481)

**Comment by F33RNI** [comment]
Yes, there is really no issue here, because I don't understand what pictures you are trying to feed to Bing AI even though `README.md` says that **it doesn't accept images as input**
