### ISSUE TITLE
Auto cookie google bard

### ISSUE THREAD

**Issue by kaifsarkar123** [F33RNI/GPT-Telegramus#80]
Is there a way to add auto cookie in google bard as after some time the Bard cookie changed and again we have to add is there is any way to fix that

**Comment by F33RNI** [comment]
Use another account and do not log into it through a normal browser.  GPT-Telegramus automatically updates bard cookies after every request (updates existing file)

**Comment by F33RNI** [comment]
For me Bard has been working without problems all this time after the last release 24/7 with US proxy

**Comment by kaifsarkar123** [comment]
I think microsoft know is against the unofficial usage that's why it has multiple issues 😄

**Comment by Ron-yos58** [comment]
i'm follow your instruction but have same error with bard: this is the reply comment

❌ Error: HTTPSConnectionPool(host='bard.google.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Cannot connect to proxy.', OSError('Tunnel connection failed: 502 Bad Gateway')))

> For me Bard has been working without problems all this time after the last release 24/7 with US proxy

**Comment by F33RNI** [comment]
> i followed your instructions but have the same error in module bard: this is a reply comment
> 
> ❌ Error: HTTPSConnectionPool(host='bard.google.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Cannot connect to proxy.', OSError('Tunnel connection failed: 502 Bad Gateway')))
> 
> > For me Bard has been working without problems all this time after the last release 24/7 with US proxy
> 
> 

Most likely this is a proxy error. It looks like that Bard only accepts USA IPs. If you do not live in the USA or another country where it works, you will need to either make your own proxy or buy it and specify in format `http://user:password@proxyip:port`.

p.s. GPT-Telegramus auto-proxy feature not tested for a very long time and most likely will not work for Bard

**Comment by F33RNI** [comment]
I have a fairly cheap US proxy that I bought. Through a Chrome extension, I access Bard using this proxy, make some requests, and download cookies. After that, I use my proxy's IP in GPT-Telegramus and never log into this Google account through a browser again.
