### ISSUE TITLE
The bot does not go further than selecting a language (the buttons do not work(?))

### ISSUE THREAD

**Issue by f9rr4r1** [F33RNI/GPT-Telegramus#81]
thats all
![image](https://github.com/F33RNI/GPT-Telegramus/assets/64973590/98dec45f-df06-4d67-98c3-02267a8fd110)

Before that, before starting, I got the error “missing "langdetect" module”. I installed it, everything started fine, but there was no progress beyond selecting the language.

**Comment by f9rr4r1** [comment]
I navigated around the bot using /help, no buttons work

**Comment by F33RNI** [comment]
What is your OS and Python versions?

**Comment by F33RNI** [comment]
Please try using official Telegram client, Python 3.10 and follow the [get-started](https://github.com/F33RNI/GPT-Telegramus#-get-started) section

**Comment by F33RNI** [comment]
Are you using an official telegram client?
Also, please provide logs

**Comment by F33RNI** [comment]
Please read the [🌎 Proxy to bypass geo-blocking](https://github.com/F33RNI/GPT-Telegramus#-proxy-to-bypass-geo-blocking) section

As you can see:

NOT TESTED AND MOST LIKELY WILL NOT WORK
I won't respond to the issue if it's related to auto proxy

**Comment by F33RNI** [comment]
For now try to disable any proxies and check buttons again

**Comment by f9rr4r1** [comment]
> For now try to disable any proxies and check buttons again

I'm from Russia, but buttons for choose language may work without proxy?
![image](https://github.com/F33RNI/GPT-Telegramus/assets/64973590/e522af4a-2cb4-49bf-97d5-6381781b21f6)

**Comment by F33RNI** [comment]
Хмм... Очень странная ситуация...
Просто из за этого прокси часто виснет весь бот, и я думала тут такая же ситуация (
Видимо дело не в прокси. Напишите мне в ТГ пожалуйста @f33rni

**Comment by f9rr4r1** [comment]
Решение: поменять токен бота.
Спасибо F33RNI за помощь.)
