### ISSUE TITLE
All modules works unless ChatGPT.

### ISSUE THREAD

**Issue by chelaxian** [F33RNI/GPT-Telegramus#82]
I use localhost API v1 - port is listen but curl can't get this URL http://127.0.0.1:9090/api/ 

Also when trying to prompt with chatgpt in telegram - timeout 120s or auth OpenAI failed.

**Comment by f9rr4r1** [comment]
У тебя работают inline кнопки?

**Comment by f9rr4r1** [comment]
> > У тебя работают inline кнопки?
> 
> да, все работает. все кнопки и все движки. не работает только частный прокси с chatgpt API v1 (с публичным работает, с тем что выше кидал)

Не знаешь как пофиксить то, что не работают inline кнопки в боте? Через команды всё работает, а кнопки не работают вообще. Запускал на своем ноуте, с впн, без прокси. Конфиг полностью настроен. Если можешь помочь, то напиши в тг, пожалуйста: @fever55

**Comment by F33RNI** [comment]
ChatGPT действительно не работал долгое время. Возможно по причине их новой капчи с белкой)
Сейчас только проверила - заработало. Для работы ChatGPT вам необходимо настроить свой Base URL Proxy, о чём написано в README

**Comment by F33RNI** [comment]
> У тебя работают inline кнопки?

Кнопки работают. Просто некоторые клиенты Телеграм выводят ошибку если кнопки не обновляются. В обновлении кнопок нет необходимости, т.к. на официальном клиенте Телеграмм всё работает

**Comment by F33RNI** [comment]
Т.к. основная тема issue была связана с неработоспособностью модуля ChatGPT, а сейчас всё работает, я закрываю Isuue.
p.s. Обновите свой accessToken (https://chat.openai.com/api/auth/session) и проверьте работает ли ChatGPTProxy и всё должно начать работать
