### ISSUE TITLE
bard cookies is working about 20 min

### ISSUE THREAD

**Issue by chelaxian** [F33RNI/GPT-Telegramus#84]
bard cookies is working about 20 min and then you get error:

`SNlM0e value not found. Double-check __Secure-1PSID value or pass it as token='xxxxx'.`

will be great if you can apply cookie rotation mechanism or using multi-cookies and try next one by dictonary array when old one stop working

**Comment by F33RNI** [comment]
Please use a proxy so that your IP does not change for Bard. Also, do not use this Google account that is set up for the bot. My cookies have been working for more than a month without problems, because GPT-Telegramus updates them itself
