### ISSUE TITLE
Bing Ai / Edge Gpt capchta error

### ISSUE THREAD

**Issue by meteaslandev** [F33RNI/GPT-Telegramus#86]
"Exception: CaptchaChallenge: User needs to solve CAPTCHA to continue." Is there an easy way to solve the captcha error? Or do we have to do this with capchta solver services?

**Comment by F33RNI** [comment]
This may be because your IP is changing. Please try to buy a cheap proxy for these purposes

**Comment by F33RNI** [comment]
After purchasing a proxy, I did not encounter this error. We need someone else to answer this issue

**Comment by F33RNI** [comment]
Sorry. I'm now faced with the same error. Now I’ll think about what’s wrong. Thanks for the issue!

**Comment by meteaslandev** [comment]
Hey thanks for answering firstly. But the new proxy method didn't worked for me. If I had to give more details, I would say that this proxy belongs to Seychelles. Do you think I should try with a new proxy?

**Comment by F33RNI** [comment]
If Bing asked you to fill out a captcha, you may need to change your proxy provider

**Comment by meteaslandev** [comment]
Wow! its worked with another proxy and different browser(this scenario I used firefox). Thanks for helping 👍
