### ISSUE TITLE
❌ Error: UnauthorizedRequest: Token issued by

### ISSUE THREAD

**Issue by Deplyapp** [F33RNI/GPT-Telegramus#92]
*❌ Error: UnauthorizedRequest: Token issued by https://sydney.bing.com/sydney is invalid (IDX10223: Lifetime v...

Clear the history and make another request or try again later.*

This error happens every time even after clearing the history and also I provided the latest cookies but not working still the same.

**Comment by F33RNI** [comment]
Sorry for the late response. This error likely occurs because our API for Bing AI cannot read cookie files after the response. This leads to the "expiration" of the history. Unfortunately, I don't yet know how to fix this. Pls clear the history if you've submitted a new request after 5-15 minutes
