### ISSUE TITLE
Error while sending images to telegram 

### ISSUE THREAD

**Issue by kaifsarkar123** [F33RNI/GPT-Telegramus#93]
![Screenshot_20231130_204226_Chrome](https://github.com/F33RNI/GPT-Telegramus/assets/139149350/19194318-dc7a-418f-a0ee-0b1d127804c3)
It is showing this error while sending the images generated with bard

**Comment by F33RNI** [comment]
Fixed
https://github.com/F33RNI/GPT-Telegramus/pull/94

**Comment by F33RNI** [comment]
https://github.com/F33RNI/GPT-Telegramus/pull/94/commits/ce9524fc31bb776bc61994b50d60ed2ece941109
```python
# Collect media group
media_group = []
for url in request_response.response:
    media_group.append(InputMediaPhoto(media=url))
    if not url.lower().endswith(".svg"):
        media_group.append(InputMediaPhoto(media=url))

# Send it
media_group_message_id = (await (telegram.Bot(config["telegram"]["api_key"]).sendMediaGroup(
```
