### ISSUE TITLE
Bot generation code very slow

### ISSUE THREAD

**Issue by vuisme** [F33RNI/GPT-Telegramus#95]
Bot generation code very slow and almost time out, even though you've set a 480-second timeout. Text generation works fine
![image](https://github.com/F33RNI/GPT-Telegramus/assets/96235876/01f01a1a-6977-4ce3-98f3-5dd5f189e18f)

**Comment by vuisme** [comment]
https://github.com/F33RNI/GPT-Telegramus/assets/96235876/719526de-057a-4320-9feb-dee3357c6692

**Comment by Deplyapp** [comment]
How did you use the chatgpt it's not working for me

**Comment by vuisme** [comment]
> How did you use the chatgpt it's not working for me can you please tell me how to use it.

I'm using other proxy: https://github.com/pandora-next/deploy

**Comment by Deplyapp** [comment]
> > How did you use the chatgpt it's not working for me can you please tell me how to use it.
> 
> I'm using other proxy: https://github.com/pandora-next/deploy

I have to host this

**Comment by vuisme** [comment]
My method is: Access Token (take from https://chat.openai.com/api/auth/session)
Proxy url: http://host/backend-api/

**Comment by Deplyapp** [comment]
![Screenshot_20231202_084353_Chrome](https://github.com/F33RNI/GPT-Telegramus/assets/151662584/8f3c0ea3-0f7c-4292-acde-46ce4aa2b981)
Thanks a lot for your help. I have tried it but it not work I got the screenshot of my config file please tell me it iam doing something wrong.

> My method is: Access Token (take from https://chat.openai.com/api/auth/session) Proxy url: http://host/backend-api/

**Comment by F33RNI** [comment]
> 
> https://github.com/F33RNI/GPT-Telegramus/assets/96235876/719526de-057a-4320-9feb-dee3357c6692
> 
> 

Why do I think this is slow?
Telegram doesn't allow to fastly spam messages, so I added a small delay that you can change in the config file

**Comment by F33RNI** [comment]
> 
> ![Screenshot_20231202_084353_Chrome](https://github.com/F33RNI/GPT-Telegramus/assets/151662584/8f3c0ea3-0f7c-4292-acde-46ce4aa2b981)
> Thanks a lot for your help. I have tried it but it not work I got the screenshot of my config file please tell me it iam doing something wrong.
> 
> > My method is: Access Token (take from https://chat.openai.com/api/auth/session) Proxy url: http://host/backend-api/
> 
> 

Please create a new issue for this. Because it's a different topic

**Comment by F33RNI** [comment]
> Bot generation code very slow and almost time out, even though you've set a 480-second timeout. Text generation works fine
> ![image](https://github.com/F33RNI/GPT-Telegramus/assets/96235876/01f01a1a-6977-4ce3-98f3-5dd5f189e18f)
> 
Try edit these lines

https://github.com/F33RNI/GPT-Telegramus/blob/master/config.json#L158-L159

**Comment by vuisme** [comment]
> > explorer_NwM9NxsOCm_4.mp4
> 
> Why do I think this is slow? Telegram doesn't allow to fastly spam messages, so I added a small delay that you can change in the config file

I will try. It's slow because on chatgpt, the answer is complete with full answer but on chatbot it's continues add word per word
