### ISSUE TITLE
Chatgpt Not working

### ISSUE THREAD

**Issue by Deplyapp** [F33RNI/GPT-Telegramus#96]
![Screenshot_20231203_102534_Telegram](https://github.com/F33RNI/GPT-Telegramus/assets/151662584/f2ac18db-5a00-4066-9edd-3d575c37e834)
I have tried but I could not use the chatgpt api type 1 I tried to host the chatgpt proxy but it not work please guide me to use chatgpt api type 1.

**Comment by Deplyapp** [comment]
If it hosted successfully when I go the the Link what should it will print on the page

**Comment by F33RNI** [comment]
https://github.com/F33RNI/GPT-Telegramus/pull/144
